//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_move
    {
        public int SubdeptID_sender { get; set; }
        public int SubdeptID_recipient { get; set; }
        public string Send { get; set; }
        public string Rec { get; set; }
        public string FIO { get; set; }
        public int Equipment_ID { get; set; }
        public string NAIMOB { get; set; }
        public string REGNO { get; set; }
        public int id_Hist { get; set; }
        public System.DateTime Data_isp { get; set; }
        public string Room { get; set; }
        public Nullable<int> Building { get; set; }
        public int BuildingID { get; set; }
        public string BuldingName { get; set; }
        public string BuildnameOld { get; set; }
        public int BuildIDOld { get; set; }
    }
}
