//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logDataChanges
    {
        public int ID { get; set; }
        public int WhoChangedID { get; set; }
        public string WhatTableChanged { get; set; }
        public int ChangedRecordID { get; set; }
        public string ChangedColumnName { get; set; }
        public System.DateTime ChangesDate { get; set; }
        public Nullable<int> OldValueNumber { get; set; }
        public string OldValueText { get; set; }
        public Nullable<float> OldValueFloat { get; set; }
        public Nullable<System.DateTime> OldValueDate { get; set; }
        public Nullable<bool> OldValueBool { get; set; }
        public int TypeChangesID { get; set; }
        public string TableIDColumnName { get; set; }
    
        public virtual tChangesTypes tChangesTypes { get; set; }
        public virtual tUsers tUsers { get; set; }
    }
}
