//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NALICH
    {
        public NALICH()
        {
            this.tFactWorkTime = new HashSet<tFactWorkTime>();
            this.tImportantEquipment = new HashSet<tImportantEquipment>();
            this.History_movement = new HashSet<History_movement>();
            this.History_spisanie = new HashSet<History_spisanie>();
        }
    
        public int ID { get; set; }
        public string KODOP { get; set; }
        public string KODKOR { get; set; }
        public string DATAZAP { get; set; }
        public int IdSubDept { get; set; }
        public int BuildingID { get; set; }
        public string W { get; set; }
        public string G { get; set; }
        public string P { get; set; }
        public string M { get; set; }
        public string PODSD { get; set; }
        public string INWNOM { get; set; }
        public int AggregateCode { get; set; }
        public string REGNO { get; set; }
        public string NAIMOB { get; set; }
        public string MARKA { get; set; }
        public string ZAWNO { get; set; }
        public string ZAWOD { get; set; }
        public string GODWYP { get; set; }
        public string DWWOD { get; set; }
        public string WUST { get; set; }
        public string KSUST { get; set; }
        public string KPUST { get; set; }
        public string POM { get; set; }
        public string SPOSK { get; set; }
        public string SPOST { get; set; }
        public string SPOSTO { get; set; }
        public Nullable<double> SMEN { get; set; }
        public Nullable<double> KOLTEK { get; set; }
        public string WRASCH { get; set; }
        public Nullable<double> KOLKSTR { get; set; }
        public Nullable<double> KOLTSTR { get; set; }
        public Nullable<double> KOLOSTR { get; set; }
        public Nullable<double> PER { get; set; }
        public string SHIFWR { get; set; }
        public Nullable<double> KUSE { get; set; }
        public Nullable<double> KUSM { get; set; }
        public Nullable<double> KATM { get; set; }
        public Nullable<double> KATE { get; set; }
        public Nullable<double> TRUDK { get; set; }
        public Nullable<double> TRUDT { get; set; }
        public Nullable<double> TRUDTO { get; set; }
        public Nullable<double> STOIM { get; set; }
        public string OBOZN { get; set; }
        public string NTEX { get; set; }
        public string DPKAP { get; set; }
        public string KOLKAP { get; set; }
        public string WPR { get; set; }
        public Nullable<double> NPR { get; set; }
        public string DPR { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public bool MainOGE { get; set; }
        public bool SubjectToInspection { get; set; }
        public bool ImportantToSafety { get; set; }
        public Nullable<System.DateTime> StartUpDate { get; set; }
        public int id_Type { get; set; }
        public Nullable<int> id_Group { get; set; }
        public Nullable<int> id_SubGroup { get; set; }
        public Nullable<int> id_Mark { get; set; }
        public Nullable<int> id_Model { get; set; }
        public Nullable<int> int_P { get; set; }
        public Nullable<int> id_TypeIsGroup { get; set; }
        public bool status_spisanie { get; set; }
    
        public virtual sprBuildings sprBuildings { get; set; }
        public virtual sprSubDept sprSubDept { get; set; }
        public virtual tAggregateCodifer tAggregateCodifer { get; set; }
        public virtual TypeISGroup TypeISGroup { get; set; }
        public virtual ICollection<tFactWorkTime> tFactWorkTime { get; set; }
        public virtual ICollection<tImportantEquipment> tImportantEquipment { get; set; }
        public virtual ICollection<History_movement> History_movement { get; set; }
        public virtual ICollection<History_spisanie> History_spisanie { get; set; }
    }
}
