//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPREntities : DbContext
    {
        public PPREntities()
            : base("name=PPREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<logDataChanges> logDataChanges { get; set; }
        public DbSet<NALICH> NALICH { get; set; }
        public DbSet<SBEZRU> SBEZRU { get; set; }
        public DbSet<sprBrigad> sprBrigad { get; set; }
        public DbSet<sprBuildings> sprBuildings { get; set; }
        public DbSet<sprEquipment> sprEquipment { get; set; }
        public DbSet<sprEquipmentGroup> sprEquipmentGroup { get; set; }
        public DbSet<sprGroup> sprGroup { get; set; }
        public DbSet<sprMark> sprMark { get; set; }
        public DbSet<sprModel> sprModel { get; set; }
        public DbSet<sprNetsSystemsFacility> sprNetsSystemsFacility { get; set; }
        public DbSet<sprReactOperationMode> sprReactOperationMode { get; set; }
        public DbSet<sprReactors> sprReactors { get; set; }
        public DbSet<sprReactSafetyClasses> sprReactSafetyClasses { get; set; }
        public DbSet<sprReairWork> sprReairWork { get; set; }
        public DbSet<sprReasonSheduleDeviation> sprReasonSheduleDeviation { get; set; }
        public DbSet<sprRepairCalc> sprRepairCalc { get; set; }
        public DbSet<sprRepairCycles> sprRepairCycles { get; set; }
        public DbSet<sprRepairMethods> sprRepairMethods { get; set; }
        public DbSet<sprRepairTypes> sprRepairTypes { get; set; }
        public DbSet<sprSeasonRepair> sprSeasonRepair { get; set; }
        public DbSet<sprSHPZ> sprSHPZ { get; set; }
        public DbSet<sprStartStopWorkLimit> sprStartStopWorkLimit { get; set; }
        public DbSet<sprSubDept> sprSubDept { get; set; }
        public DbSet<sprSubGroup> sprSubGroup { get; set; }
        public DbSet<sprTypeOfEquipment> sprTypeOfEquipment { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tAggregateCodifer> tAggregateCodifer { get; set; }
        public DbSet<tChangesTypes> tChangesTypes { get; set; }
        public DbSet<tFactWorkTime> tFactWorkTime { get; set; }
        public DbSet<tFunctionAccess> tFunctionAccess { get; set; }
        public DbSet<tImportantEquipment> tImportantEquipment { get; set; }
        public DbSet<tMainMenuItems> tMainMenuItems { get; set; }
        public DbSet<tTypeEquipmentCatalog> tTypeEquipmentCatalog { get; set; }
        public DbSet<tUserFunctions> tUserFunctions { get; set; }
        public DbSet<tUsers> tUsers { get; set; }
        public DbSet<TypeISGroup> TypeISGroup { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<vRolesFunctionAccess> vRolesFunctionAccess { get; set; }
        public DbSet<vsprSeasonRepairDepend> vsprSeasonRepairDepend { get; set; }
        public DbSet<vSubdeptsInBuildings> vSubdeptsInBuildings { get; set; }
        public DbSet<vUserFuncionAccess> vUserFuncionAccess { get; set; }
        public DbSet<vUsersRoles> vUsersRoles { get; set; }
        public DbSet<history_move> history_move { get; set; }
        public DbSet<History_movement> History_movement { get; set; }
        public DbSet<History_spisanie> History_spisanie { get; set; }
        public DbSet<spisanie_history> spisanie_history { get; set; }
        public DbSet<ElectronicArchive> ElectronicArchive { get; set; }
    }
}
