//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBEZRU
    {
        public string REGNO { get; set; }
        public string PRAG { get; set; }
        public string KLGBEZ { get; set; }
        public string RU { get; set; }
        public int ID { get; set; }
    }
}
