//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class spisanie_history
    {
        public int ID { get; set; }
        public string ShortName { get; set; }
        public string BuldingName { get; set; }
        public string POM { get; set; }
        public string REGNO { get; set; }
        public string INWNOM { get; set; }
        public string SignName { get; set; }
        public string NAIMOB { get; set; }
        public string TypeCode { get; set; }
        public string GroupName { get; set; }
        public string SubGroupName { get; set; }
        public string mark { get; set; }
        public string FIO { get; set; }
        public System.DateTime Data { get; set; }
        public string TypeOfEquipment { get; set; }
        public int idGroup { get; set; }
        public int idSubGroup { get; set; }
        public string oldValue { get; set; }
        public int SubDeptCode { get; set; }
        public int id_sp { get; set; }
        public string model { get; set; }
        public bool status_spisanie { get; set; }
    }
}
