//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprBuildings
    {
        public sprBuildings()
        {
            this.NALICH = new HashSet<NALICH>();
            this.sprSubDept = new HashSet<sprSubDept>();
        }
    
        public int BuildingID { get; set; }
        public string BuldingName { get; set; }
        public bool NotAvailable { get; set; }
    
        public virtual ICollection<NALICH> NALICH { get; set; }
        public virtual ICollection<sprSubDept> sprSubDept { get; set; }
    }
}
