//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprBrigad
    {
        public string KBR { get; set; }
        public string MASTER { get; set; }
        public string FIOBR { get; set; }
        public string KOLRAB { get; set; }
        public Nullable<double> NKW { get; set; }
        public Nullable<double> PLF { get; set; }
        public Nullable<double> TRPPR { get; set; }
        public Nullable<double> NKOR { get; set; }
        public Nullable<double> TRBR { get; set; }
    }
}
