//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprEquipment
    {
        public sprEquipment()
        {
            this.sprRepairCycles = new HashSet<sprRepairCycles>();
        }
    
        public int IdEquipment { get; set; }
        public string W { get; set; }
        public int EquipmentGroup { get; set; }
        public Nullable<int> SubGroup { get; set; }
        public Nullable<int> Model { get; set; }
        public string GroupName { get; set; }
        public string SubGroupName { get; set; }
        public string Mark { get; set; }
        public string symbol_g { get; set; }
        public string symbol_p { get; set; }
    
        public virtual sprEquipmentGroup sprEquipmentGroup { get; set; }
        public virtual ICollection<sprRepairCycles> sprRepairCycles { get; set; }
    }
}
