//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprModel
    {
        public sprModel()
        {
            this.TypeISGroup = new HashSet<TypeISGroup>();
        }
    
        public int id_model { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<TypeISGroup> TypeISGroup { get; set; }
    }
}
