//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprRepairCalc
    {
        public int RecordID { get; set; }
        public int IdSubDept { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> QuarterNumber { get; set; }
        public Nullable<double> RepairPriceC { get; set; }
        public Nullable<double> MaterialPriceC { get; set; }
        public Nullable<double> RepairPriceP { get; set; }
        public Nullable<double> MaterialPriceP { get; set; }
        public Nullable<double> RepairPriceO { get; set; }
        public Nullable<double> MaterialPriceO { get; set; }
    
        public virtual sprSubDept sprSubDept { get; set; }
    }
}
