//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprSubDept
    {
        public sprSubDept()
        {
            this.NALICH = new HashSet<NALICH>();
            this.sprRepairCalc = new HashSet<sprRepairCalc>();
            this.sprSHPZ = new HashSet<sprSHPZ>();
            this.tUsers = new HashSet<tUsers>();
            this.sprBuildings = new HashSet<sprBuildings>();
            this.History_movement = new HashSet<History_movement>();
            this.History_movement1 = new HashSet<History_movement>();
            this.History_spisanie = new HashSet<History_spisanie>();
        }
    
        public int IdSubDept { get; set; }
        public int SubDeptCode { get; set; }
        public string SubDeptName { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<NALICH> NALICH { get; set; }
        public virtual ICollection<sprRepairCalc> sprRepairCalc { get; set; }
        public virtual ICollection<sprSHPZ> sprSHPZ { get; set; }
        public virtual ICollection<tUsers> tUsers { get; set; }
        public virtual ICollection<sprBuildings> sprBuildings { get; set; }
        public virtual ICollection<History_movement> History_movement { get; set; }
        public virtual ICollection<History_movement> History_movement1 { get; set; }
        public virtual ICollection<History_spisanie> History_spisanie { get; set; }
    }
}
