//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprSHPZ
    {
        public int RecordID { get; set; }
        public int IdSubDept { get; set; }
        public string RepairType { get; set; }
        public string RepairMethod { get; set; }
        public string BalanceBill { get; set; }
        public string CostElements { get; set; }
        public string CostParticle { get; set; }
    
        public virtual sprSubDept sprSubDept { get; set; }
    }
}
