//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAggregateCodifer
    {
        public tAggregateCodifer()
        {
            this.NALICH = new HashSet<NALICH>();
        }
    
        public int SignID { get; set; }
        public string SignName { get; set; }
        public string SignCode { get; set; }
    
        public virtual ICollection<NALICH> NALICH { get; set; }
    }
}
