//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChangesTypes
    {
        public tChangesTypes()
        {
            this.logDataChanges = new HashSet<logDataChanges>();
        }
    
        public int ChangesTypeID { get; set; }
        public string ChangesTypeName { get; set; }
    
        public virtual ICollection<logDataChanges> logDataChanges { get; set; }
    }
}
