//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFactWorkTime
    {
        public int RecordID { get; set; }
        public int EquipmentID { get; set; }
        public string EquipmentRegNum { get; set; }
        public int FactWorkHours { get; set; }
        public int AverageStatHours { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<System.DateTime> LastPeriodStart { get; set; }
        public Nullable<System.DateTime> LastPeriodEnd { get; set; }
    
        public virtual NALICH NALICH { get; set; }
    }
}
