//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFunctionAccess
    {
        public int AccessRecordID { get; set; }
        public int FunctionID { get; set; }
        public int IsAvailableTo { get; set; }
        public bool AccessTypeUser { get; set; }
    
        public virtual tUserFunctions tUserFunctions { get; set; }
    }
}
