//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tImportantEquipment
    {
        public int RecordID { get; set; }
        public int EquipmentID { get; set; }
        public int SecurityClassID { get; set; }
        public int ReactorID { get; set; }
    
        public virtual NALICH NALICH { get; set; }
        public virtual sprReactors sprReactors { get; set; }
        public virtual sprReactSafetyClasses sprReactSafetyClasses { get; set; }
    }
}
