//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMainMenuItems
    {
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public int FunctionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string RussianName { get; set; }
        public int ItemPriority { get; set; }
        public string URLPath { get; set; }
    
        public virtual tUserFunctions tUserFunctions { get; set; }
    }
}
