//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsers
    {
        public tUsers()
        {
            this.logDataChanges = new HashSet<logDataChanges>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.History_movement = new HashSet<History_movement>();
            this.History_spisanie = new HashSet<History_spisanie>();
        }
    
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public Nullable<int> SubDeptID { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<logDataChanges> logDataChanges { get; set; }
        public virtual sprSubDept sprSubDept { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<History_movement> History_movement { get; set; }
        public virtual ICollection<History_spisanie> History_spisanie { get; set; }
    }
}
