//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeISGroup
    {
        public TypeISGroup()
        {
            this.NALICH = new HashSet<NALICH>();
        }
    
        public int id { get; set; }
        public int idType { get; set; }
        public int idGroup { get; set; }
        public Nullable<int> idSubGroup { get; set; }
        public Nullable<int> idMark { get; set; }
        public Nullable<int> idModel { get; set; }
        public string oldValue { get; set; }
    
        public virtual ICollection<NALICH> NALICH { get; set; }
        public virtual sprGroup sprGroup { get; set; }
        public virtual sprMark sprMark { get; set; }
        public virtual sprModel sprModel { get; set; }
        public virtual sprSubGroup sprSubGroup { get; set; }
        public virtual sprTypeOfEquipment sprTypeOfEquipment { get; set; }
    }
}
