//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vsprSeasonRepairDepend
    {
        public int AvailabilityID { get; set; }
        public string Availability { get; set; }
        public int EarlyStartRepairID { get; set; }
        public string StartWorkLimit { get; set; }
        public int LateStopRepairID { get; set; }
        public string StopWorkLimit { get; set; }
    }
}
