//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSubdeptsInBuildings
    {
        public string BuldingName { get; set; }
        public string SubDeptName { get; set; }
        public int BuildingID { get; set; }
        public int SubDeptCode { get; set; }
        public int IdSubDept { get; set; }
        public bool NotAvailable { get; set; }
    }
}
